on:
  push:
    branches:
      - master

name: 'MyShellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2059 -e SC2034 -e SC1090
      with:
        ignore_paths: ignoreme ignoremetoo
        ignore_names: ignorable.sh
        severity: error
        scandir: '.'
        additional_files: 'run finish'
        format: gcc
        
